services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: 'q1Sh-9_ISia_zwGINzRvyQ'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - betodd_net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file: ./.env
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - betodd_net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=betodds
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: betodd-api
    env_file: ./.env
    ports:
      - "4000:4000"
    depends_on:
      - kafka
      - mongodb
    environment:
      KAFKA_BROKERS: "localhost:29092"
      RELOAD: true
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - betodd_net
  

volumes:
  dbdata:
  kafka_data:
    driver: local

networks:
  betodd_net:
    name: betodd-kafka-net